# Generated by Django 5.2.1 on 2025-05-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="bio_translated",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cv",
            name="firstname_translated",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="cv",
            name="lastname_translated",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="description_translated",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="title_translated",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="skill",
            name="level_translated",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="skill",
            name="name_translated",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
